### ISSUE TITLE
?: (urls.W002) Your URL pattern '^/$' [name='sitetree_treeitem_changelist'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.

### ISSUE THREAD

**Issue by bnisevic** [idlesign/django-sitetree#203]
We get this warning on runserver:

?: (urls.W002) Your URL pattern '^/$' [name='sitetree_treeitem_changelist'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.

**Comment by mansonul** [comment]
Check out this link:

https://github.com/idlesign/django-sitetree/commit/3b18781

**Comment by bnisevic** [comment]
But, how this is not in the current release?

**Comment by idlesign** [comment]
Thank you for the report. I should recheck the issue in a week or two, when I home with full web access.2:50, 11 августа 2016 г., Dragos Nicu <notifications@github.com>:Check out this link: 3b18781 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by idlesign** [comment]
Relates to #199

**Comment by idlesign** [comment]
Should be fixed in `master`. Feel free to reopen if required.
