### ISSUE TITLE
SiteTree class not returning current item

### ISSUE THREAD

**Issue by iwalucas** [idlesign/django-sitetree#294]
I am pulling the current tree on a middleware (to check for custom permissions), I am using the delivered `from sitetree.sitetreeapp import get_sitetree`.
This is having some intermittent behavior, some urls it works and some it doesnt.

This is my code snippet, maybe I am doing something wrong, not sure:

```
tree = get_sitetree()
tree.init({'request':request})
tree_item = tree.get_tree_current_item('my_tree_alias')
```
The `tree_item` variable is being set to None on some cases

**Comment by idlesign** [comment]
It's hard to say what's going on from your description: what are those urls it resolved, and what are those is doesn't.
To investigate it further you may try to get current item in some view. If it works, then the issue might be related to middleware (e.g. ordering), otherwise we need more information about urls.
