### ISSUE TITLE
Building and using a dynamic menu

### ISSUE THREAD

**Issue by asoupper** [idlesign/django-sitetree#311]
Hi there,
I'd like to create one single menu for my django web site. Some features are isolated in sub apps.
I created the static structure of the menu in the sitetrees.py of the main project:
```
# in main_project/sitetrees.py

sitetrees = (
  tree('main' , items=[
    item('Home', 'index', alias='home'),
    item('Admin', 'admin:index', alias='admin'),
    item('About', 'about', alias='about'),
  ]
)
```

Then in each of my sub apps, I created the dedicated menu for example:
```
# in app1/sitetrees.py

sitetrees = (
  tree('app1', items=[
    item('App1 Homepage', 'app1:index'),
    item('App1 FeatureA', 'app1:feature_a'),
  ]
)
```

I'd like to obtain the following tree:
main
 - Home
 - Application 1
   - App1 Homepage
   - App1 FeatureA
 - Admin
 - About

How to correctly write the register_dynamic_trees call?
How to reference the generated menu in the sitetree_menu tag ?

Thanks for your support

**Comment by idlesign** [comment]
Hi,

The main idea with the dynamic trees if you want all of them to be gathered into one tree, is attaching them to existing trees with the help of aliases.

Another thing to consider when your trees are in different apps is that for them in order to be attached as a subtrees, the base tree must exist. So basically you need some base three in the app that is loaded before others.

Docs are showing an example:
```
compose_dynamic_tree('books', target_tree_alias='main', parent_tree_item_alias='for_books'),
```

The default for `parent_tree_item_alias` is `root`.

So for your example something like the following may be of use
```
register_dynamic_trees(compose_dynamic_tree(sitetrees, target_tree_alias='main'))
```

**Comment by idlesign** [comment]
Considered closed.
